# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/derulin/Downloads/twtxtc/twtxtc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/derulin/Downloads/twtxtc/twtxtc

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/derulin/Downloads/twtxtc/twtxtc/CMakeFiles /home/derulin/Downloads/twtxtc/twtxtc/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/derulin/Downloads/twtxtc/twtxtc/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named twtxtc

# Build rule for target.
twtxtc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 twtxtc
.PHONY : twtxtc

# fast build rule for target.
twtxtc/fast:
	$(MAKE) -f CMakeFiles/twtxtc.dir/build.make CMakeFiles/twtxtc.dir/build
.PHONY : twtxtc/fast

cJSON/cJSON.o: cJSON/cJSON.c.o

.PHONY : cJSON/cJSON.o

# target to build an object file
cJSON/cJSON.c.o:
	$(MAKE) -f CMakeFiles/twtxtc.dir/build.make CMakeFiles/twtxtc.dir/cJSON/cJSON.c.o
.PHONY : cJSON/cJSON.c.o

cJSON/cJSON.i: cJSON/cJSON.c.i

.PHONY : cJSON/cJSON.i

# target to preprocess a source file
cJSON/cJSON.c.i:
	$(MAKE) -f CMakeFiles/twtxtc.dir/build.make CMakeFiles/twtxtc.dir/cJSON/cJSON.c.i
.PHONY : cJSON/cJSON.c.i

cJSON/cJSON.s: cJSON/cJSON.c.s

.PHONY : cJSON/cJSON.s

# target to generate assembly for a file
cJSON/cJSON.c.s:
	$(MAKE) -f CMakeFiles/twtxtc.dir/build.make CMakeFiles/twtxtc.dir/cJSON/cJSON.c.s
.PHONY : cJSON/cJSON.c.s

cJSON/cJSON_Utils.o: cJSON/cJSON_Utils.c.o

.PHONY : cJSON/cJSON_Utils.o

# target to build an object file
cJSON/cJSON_Utils.c.o:
	$(MAKE) -f CMakeFiles/twtxtc.dir/build.make CMakeFiles/twtxtc.dir/cJSON/cJSON_Utils.c.o
.PHONY : cJSON/cJSON_Utils.c.o

cJSON/cJSON_Utils.i: cJSON/cJSON_Utils.c.i

.PHONY : cJSON/cJSON_Utils.i

# target to preprocess a source file
cJSON/cJSON_Utils.c.i:
	$(MAKE) -f CMakeFiles/twtxtc.dir/build.make CMakeFiles/twtxtc.dir/cJSON/cJSON_Utils.c.i
.PHONY : cJSON/cJSON_Utils.c.i

cJSON/cJSON_Utils.s: cJSON/cJSON_Utils.c.s

.PHONY : cJSON/cJSON_Utils.s

# target to generate assembly for a file
cJSON/cJSON_Utils.c.s:
	$(MAKE) -f CMakeFiles/twtxtc.dir/build.make CMakeFiles/twtxtc.dir/cJSON/cJSON_Utils.c.s
.PHONY : cJSON/cJSON_Utils.c.s

twtxt.o: twtxt.c.o

.PHONY : twtxt.o

# target to build an object file
twtxt.c.o:
	$(MAKE) -f CMakeFiles/twtxtc.dir/build.make CMakeFiles/twtxtc.dir/twtxt.c.o
.PHONY : twtxt.c.o

twtxt.i: twtxt.c.i

.PHONY : twtxt.i

# target to preprocess a source file
twtxt.c.i:
	$(MAKE) -f CMakeFiles/twtxtc.dir/build.make CMakeFiles/twtxtc.dir/twtxt.c.i
.PHONY : twtxt.c.i

twtxt.s: twtxt.c.s

.PHONY : twtxt.s

# target to generate assembly for a file
twtxt.c.s:
	$(MAKE) -f CMakeFiles/twtxtc.dir/build.make CMakeFiles/twtxtc.dir/twtxt.c.s
.PHONY : twtxt.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... twtxtc"
	@echo "... edit_cache"
	@echo "... cJSON/cJSON.o"
	@echo "... cJSON/cJSON.i"
	@echo "... cJSON/cJSON.s"
	@echo "... cJSON/cJSON_Utils.o"
	@echo "... cJSON/cJSON_Utils.i"
	@echo "... cJSON/cJSON_Utils.s"
	@echo "... twtxt.o"
	@echo "... twtxt.i"
	@echo "... twtxt.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

